CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_NAME NVARCHAR(100) NOT NULL,
    CUSTOMER_SURNAME NVARCHAR(100) NOT NULL,
    CUSTOMER_EMAIL NVARCHAR(200),
    CUSTOMER_PHONE NVARCHAR(50)
);


CREATE TABLE AUTHOR (
    AUTHOR_ID INT IDENTITY(1,1) PRIMARY KEY,
    AUTHOR_NAME NVARCHAR(100) NOT NULL,
    AUTHOR_SURNAME NVARCHAR(100) NOT NULL,
    AUTHOR_EMAIL NVARCHAR(200)
);


CREATE TABLE ORDER_TYPE (
    ORDER_ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    DATA_RECEIPT_ORDER DATE NOT NULL,
    DATA_EXEC_ORDER DATE NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (CUSTOMER_ID) REFERENCES dbo.CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE ORDER_EXEC (
    ORDER_EXEC_ID INT IDENTITY(1,1) PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    DATE_EXEC DATE NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDER_TYPE(ORDER_ID)
);


CREATE TABLE BOOK (
    BOOK_ID INT IDENTITY(1,1) PRIMARY KEY,
    BOOK_TITLE NVARCHAR(200) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    BOOK_PUBLICATION NVARCHAR(200),
    BOOK_PRICE DECIMAL(10,2),
    ORDER_ID INT NOT NULL,

    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDER_TYPE(ORDER_ID)
);


CREATE TABLE JOURNAL (
    JOURNAL_ID INT IDENTITY(1,1) PRIMARY KEY,
    JOURNAL_TITLE NVARCHAR(200) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    JOURNAL_PUBLICATION NVARCHAR(200),
    JOURNAL_PRICE DECIMAL(10,2),
    ORDER_ID INT NOT NULL,

    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDER_TYPE(ORDER_ID)
);

CREATE TABLE MANGA (
    MANGA_ID INT IDENTITY(1,1) PRIMARY KEY,
    MANGA_TITLE NVARCHAR(200) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    MANGA_PUBLICATION NVARCHAR(200),
    MANGA_PRICE DECIMAL(10,2),
    ORDER_ID INT NOT NULL,

    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDER_TYPE(ORDER_ID)
);