SELECT * FROM BOOK
WHERE BOOK_PRICE < 17;

SELECT BOOK_TITLE, AUTHOR_ID, BOOK_PRICE
FROM BOOK
WHERE BOOK_PRICE BETWEEN 11 AND 13;

SELECT MANGA_TITLE, MANGA_PRICE
FROM MANGA
WHERE MANGA_TITLE LIKE '[MNK]%';

SELECT JOURNAL_ID, JOURNAL_TITLE, JOURNAL_PRICE
FROM JOURNAL
ORDER BY JOURNAL_PRICE DESC;

SELECT O.ORDER_ID, C.CUSTOMER_NAME, C.CUSTOMER_SURNAME, B.BOOK_TITLE, O.AMOUNT
FROM ORDER_TYPE O
JOIN CUSTOMER C ON O.CUSTOMER_ID = C.CUSTOMER_ID
LEFT JOIN BOOK B ON O.ORDER_ID = B.ORDER_ID;

SELECT O.CUSTOMER_ID, O.AMOUNT, E.ORDER_EXEC_ID, E.DATE_EXEC
FROM ORDER_TYPE O
INNER JOIN ORDER_EXEC E ON O.ORDER_ID = E.ORDER_ID;

SELECT O.ORDER_ID, C.CUSTOMER_NAME, C.CUSTOMER_SURNAME, B.BOOK_TITLE, O.AMOUNT
FROM ORDER_TYPE O
JOIN CUSTOMER C ON O.CUSTOMER_ID = C.CUSTOMER_ID
RIGHT JOIN BOOK B ON O.ORDER_ID = B.ORDER_ID;

SELECT * FROM MANGA 
CROSS JOIN BOOK

SELECT CUSTOMER_ID, COUNT(*) AS TotalOrders
FROM ORDER_TYPE
GROUP BY CUSTOMER_ID;

SELECT AUTHOR_ID, AVG(BOOK_PRICE) AS AveragePrice
FROM BOOK
GROUP BY AUTHOR_ID;

SELECT AUTHOR_ID, MAX(BOOK_PRICE) AS MaxPrice
FROM BOOK
GROUP BY AUTHOR_ID;

SELECT MANGA_ID, MANGA_TITLE, MANGA_PRICE, 
       MANGA_PRICE * 0.9 AS PriceAfterDiscount, 
       (MANGA_PRICE * 0.9) * 1.05 AS FinalPrice
FROM MANGA;

SELECT BOOK_ID, BOOK_TITLE, BOOK_PRICE, 
       BOOK_PRICE - (SELECT AVG(BOOK_PRICE) FROM BOOK) AS PriceDifference
FROM BOOK;

CREATE VIEW View_CheapBooks AS
SELECT BOOK_ID, BOOK_TITLE, BOOK_PRICE
FROM BOOK
WHERE BOOK_PRICE < 500;

SELECT * FROM View_CheapBooks;