CREATE TRIGGER trg_book_insert
ON BOOK 
AFTER INSERT
AS
BEGIN
    PRINT 'New book has been inserted into BOOK';
END;

SELECT * FROM BOOK

INSERT INTO BOOK (BOOK_TITLE, AUTHOR_ID, BOOK_PUBLICATION, BOOK_PRICE)
VALUES 
('New book 2', 10, 'Public house', 18.99);

CREATE TRIGGER trg_author_no_insert
ON AUTHOR
INSTEAD OF INSERT
AS
BEGIN
    PRINT 'Insertion into AUTHOR is blocked!';
    ROLLBACK;
END;

INSERT INTO AUTHOR (AUTHOR_NAME, AUTHOR_SURNAME, AUTHOR_EMAIL)
VALUES ('Name', 'Surname', 'someonesEmail@example.com');

CREATE TRIGGER trg_manga_update
ON MANGA
AFTER UPDATE
AS
BEGIN
    PRINT 'A MANGA record has been updated';
    SELECT * FROM INSERTED;
    SELECT * FROM DELETED;
END;
UPDATE MANGA
SET MANGA_PRICE = 2995.99
WHERE MANGA_TITLE = 'Naruto Vol. 1';

CREATE TRIGGER trg_customer_no_update
ON ORDER_EXEC
INSTEAD OF UPDATE
AS
BEGIN
    PRINT 'Updating ORDER_EXEC is blocked!';
    ROLLBACK;
END;
UPDATE ORDER_EXEC
SET AMOUNT = 2000
WHERE ORDER_EXEC_ID = 1;

ALTER TABLE ORDER_EXEC
DROP CONSTRAINT FK__ORDER_EXE__ORDER__3D5E1FD2;

ALTER TABLE ORDER_EXEC
ADD CONSTRAINT FR_ORDER_EXEC_ORDER
FOREIGN KEY(ORDER_ID) REFERENCES ORDER_TYPE(ORDER_ID)
ON DELETE CASCADE;


CREATE TRIGGER trg_delete_orderExec
ON ORDER_EXEC
FOR DELETE
AS
BEGIN
    PRINT 'Order execution records deleted';
	SELECT ORDER_EXEC_ID, GETDATE() AS DeletedAt
    FROM DELETED;
END;

DELETE FROM ORDER_EXEC
WHERE ORDER_EXEC_ID IN (
    SELECT TOP 2 ORDER_EXEC_ID
    FROM ORDER_EXEC
    ORDER BY DATE_EXEC DESC
);

CREATE TRIGGER trg_Journal_Prevent_Delete
ON JOURNAL
INSTEAD OF DELETE
AS
BEGIN
    PRINT 'Deletion from JOURNAL is blocked!';
    ROLLBACK;
END;
DELETE FROM JOURNAL
WHERE JOURNAL_ID = 1;